/* Faithfully ported from /Users/deepgunner/Desktop/Repos/Huvugalu/huvugalu.html */

export const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
export const MONTH_START = [0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334];
export const MONTH_END = [30, 58, 89, 119, 150, 180, 211, 242, 272, 303, 333, 364];
export const YEAR_DAYS = 365;

const d = (m, day) => MONTH_START[m - 1] + day - 1;
const w = (m, day) => MONTH_START[m - 1] + day - 1 + 365;

/* Issar-verified 10-species master palette. Each species has one or more bloom
   windows; `peakStart`/`peakEnd` mark the saturated heart of each window. */
const W = (s, e, ps, pe) => ({ start: s, end: e, peakStart: ps, peakEnd: pe });

export const SPECIES_LEGACY_PLACEHOLDER = [
  { id: 'bombax-ceiba', common: 'Red Silk Cotton', botanical: 'Bombax ceiba', role: 'Primary Anchor',
    color: '#B91C1C', colorName: 'Crimson Red',
    macroStart: d(1, 1), macroEnd: d(2, 15), peakSegments: [[d(1, 15), d(2, 15)]],
    durability: 'Medium · 5–7 days',
    dynamics: 'Heavy crimson cups drop onto paths as early pink tunnels and scarlet domes ignite overhead.',
    bareBranches: true },
  { id: 'tabebuia-rosea', common: 'Pink Trumpet Tree', botanical: 'Tabebuia rosea', role: 'Primary Anchor',
    color: '#F4A6C1', colorName: 'Soft Pink',
    macroStart: d(1, 15), macroEnd: d(3, 10), peakSegments: [[d(1, 15), d(3, 10)]],
    durability: 'High · 8–10 days',
    dynamics: 'Shifting winter reds yield to an expanding, completely leaf-free pink street tunnel.',
    bareBranches: true },
  { id: 'butea-monosperma', common: 'Flame of the Forest', botanical: 'Butea monosperma', role: 'Primary Anchor',
    color: '#E85D2F', colorName: 'Orange Scarlet',
    macroStart: d(2, 1), macroEnd: d(3, 15), peakSegments: [[d(2, 15), d(3, 10)]],
    durability: 'High · 10–14 days',
    dynamics: 'Crooked native orange-scarlet branches frame the emerging pink and purple exotic pastels.',
    bareBranches: true },
  { id: 'jacaranda', common: 'Jacaranda', botanical: 'Jacaranda mimosifolia', role: 'Primary Anchor',
    color: '#7C6FCB', colorName: 'Blue-Mauve',
    macroStart: d(2, 15), macroEnd: d(3, 25), peakSegments: [[d(2, 15), d(3, 25)]],
    durability: 'High · 10–14 days',
    dynamics: 'A cooling, lacy blue-mauve canopy cloud replaces the winter pinks and greets early summer golds.' },
  { id: 'tabebuia-aurea', common: 'Yellow Tabebuia', botanical: 'Tabebuia aurea', role: 'Layered Partner',
    color: '#F5C518', colorName: 'Bright Yellow',
    macroStart: d(3, 1), macroEnd: d(4, 10), peakSegments: [[d(3, 1), d(3, 25)]],
    durability: 'Medium · 8–10 days',
    dynamics: 'Sharp, paper-thin golden-yellow blossoms open on corky wood as the purple haze recedes.' },
  { id: 'cassia-javanica', common: 'Java Cassia', botanical: 'Cassia javanica', role: 'Primary Anchor',
    color: '#E26A8F', colorName: 'Rosy Pink',
    macroStart: d(4, 1), macroEnd: d(5, 10), peakSegments: [[d(4, 15), d(5, 10)]],
    durability: 'High · 12–15 days',
    dynamics: 'Spreading rosy-pink and white suburban ribbons trail along roadsides as spring golds fade.' },
  { id: 'peltophorum', common: 'Copperpod', botanical: 'Peltophorum pterocarpum', role: 'Layered Partner',
    color: '#E8B400', colorName: 'Bright Yellow',
    macroStart: d(3, 15), macroEnd: d(5, 15), peakSegments: [[d(4, 15), d(5, 15)]],
    durability: 'Very High · 2 months',
    dynamics: 'Bushy yellow crowns drop golden flakes, carpeting curbs beneath emerging red umbrella ceilings.' },
  { id: 'delonix-regia', common: 'Gulmohar', botanical: 'Delonix regia', role: 'Primary Anchor',
    color: '#FF5722', colorName: 'Fiery Orange-Red',
    macroStart: d(4, 20), macroEnd: d(6, 15), peakSegments: [[d(5, 1), d(6, 10)]],
    durability: 'Very High · 6–8 weeks',
    dynamics: 'Skyline Roof — a flat horizontal ceiling of bright fire-orange over lower-tier assets.' },
  { id: 'cassia-fistula', common: 'Amaltas', botanical: 'Cassia fistula', role: 'Layered Partner',
    color: '#F2B705', colorName: 'Golden Yellow',
    macroStart: d(5, 1), macroEnd: d(6, 20), peakSegments: [[d(5, 1), d(6, 10)]],
    durability: 'High · 3 weeks',
    dynamics: 'Vertical Stratification — long golden chains drop straight down as chandeliers beneath the red ceiling.' },
  { id: 'samanea-saman', common: 'Rain Tree', botanical: 'Samanea saman', role: 'Primary Anchor',
    color: '#F2B6C8', colorName: 'Pink-Tipped',
    macroStart: d(6, 15), macroEnd: d(8, 15), peakSegments: [[d(6, 15), d(7, 25)]],
    durability: 'Very High · 2 months',
    dynamics: 'Sprawling umbrellas drop millions of pink-tipped filaments to weave a fuzzy mat on wet grass.' },
  { id: 'colvillea', common: "Colville's Glory", botanical: 'Colvillea racemosa', role: 'Primary Anchor',
    color: '#F08A3A', colorName: 'Bright Orange',
    macroStart: d(8, 1), macroEnd: d(9, 20), peakSegments: [[d(9, 1), d(9, 20)]],
    durability: 'Medium · 7–10 days',
    dynamics: 'Sky Shooter — isolated orange cones spike upwards, operating strictly above standard green tree lines.' },
  { id: 'cassia-multijuga', common: 'Golden Cassia', botanical: 'Cassia multijuga', role: 'Primary Anchor',
    color: '#F5C518', colorName: 'Butter Yellow',
    macroStart: d(8, 15), macroEnd: d(10, 15),
    peakSegments: [[d(9, 1), d(9, 20)], [d(10, 1), d(10, 15)]],
    durability: 'Very High · 2 months',
    dynamics: 'Autumn Gold — a massive second wave of uniform butter-yellow across suburban extensions.' },
  { id: 'spathodea', common: 'African Tulip', botanical: 'Spathodea campanulata', role: 'Primary Anchor',
    color: '#DC2626', colorName: 'Scarlet Red',
    macroStart: d(10, 1), macroEnd: d(12, 10),
    peakSegments: [[d(10, 1), d(10, 15)], [d(11, 15), d(12, 10)]],
    durability: 'Very High · 10 weeks',
    dynamics: 'Tall, sporadic scarlet domes warm the cooling autumn air before the winter white arrives.' },
  { id: 'millingtonia', common: 'Indian Cork Tree', botanical: 'Millingtonia hortensis', role: 'Primary Anchor',
    color: '#FAFAF7', colorName: 'Pure White',
    macroStart: d(11, 15), macroEnd: w(1, 10), peakSegments: [[d(11, 15), d(12, 10)]],
    durability: 'High · 2 weeks',
    dynamics: 'The White Carpet — night-blooming fragrant white tubes blanket cold, misty winter morning roadways.' },
  { id: 'grevillea', common: 'Silver Oak', botanical: 'Grevillea robusta', role: 'Permanent Canopy',
    color: '#4A7C59', colorName: 'Deep Evergreen',
    macroStart: 0, macroEnd: 364, peakSegments: [[0, 364]],
    durability: 'Permanent Structure',
    dynamics: 'Towering architectural backdrop that provides constant structural green across all seasons.' },
];

export const SPECIES = [
  { id: 'slv', code: 'SLV', common: 'Silver Oak', botanical: 'Grevillea robusta',
    origin: 'Australia', color: '#7A9E96', colorName: 'Evergreen Slate', role: 'Permanent Canopy',
    peak: 'Year-round',
    windows: [W(0, 364, 0, 364)] },
  { id: 'ery', code: 'ERY', common: 'Coral Tree', botanical: 'Erythrina variegata',
    origin: 'Indo-Pacific', color: '#C94028', colorName: 'Scarlet Coral',
    peak: 'January (Dec return)',
    windows: [
      W(d(12, 1), 364, d(12, 15), 364),
      W(0, d(1, 31), 0, d(1, 25)),
    ] },
  { id: 'jac', code: 'JAC', common: 'Jacaranda', botanical: 'Jacaranda mimosifolia',
    origin: 'South America', color: '#6B55A0', colorName: 'Blue-Mauve',
    peak: 'March (Feb–Apr)',
    windows: [W(d(2, 1), d(4, 20), d(3, 1), d(3, 31))] },
  { id: 'tab', code: 'TAB', common: 'Pink Trumpet', botanical: 'Tabebuia rosea',
    origin: 'Central America', color: '#C84878', colorName: 'Rose Pink',
    peak: 'February + Oct–Nov',
    windows: [
      W(d(2, 1), d(3, 10), d(2, 8), d(2, 25)),
      W(d(10, 1), d(12, 25), d(10, 15), d(11, 15)),
    ] },
  { id: 'tye', code: 'TYE', common: 'Tree of Gold', botanical: 'Tabebuia argentea',
    origin: 'South America', color: '#E6B800', colorName: 'Pure Gold',
    peak: 'February',
    windows: [W(d(2, 1), d(2, 28), d(2, 5), d(2, 25))] },
  { id: 'aml', code: 'AML', common: 'Amaltas', botanical: 'Cassia fistula',
    origin: 'South Asia', color: '#C89820', colorName: 'Golden Yellow',
    peak: 'April (Apr–May)',
    windows: [W(d(4, 1), d(5, 15), d(4, 10), d(5, 5))] },
  { id: 'gul', code: 'GUL', common: 'Gulmohur', botanical: 'Delonix regia',
    origin: 'Madagascar', color: '#D03A18', colorName: 'Flame Orange',
    peak: 'May (Apr–Jun)',
    windows: [W(d(4, 1), d(6, 15), d(5, 1), d(5, 31))] },
  { id: 'poi', code: 'POI', common: 'Pride of India', botanical: 'Lagerstroemia speciosa',
    origin: 'South Asia', color: '#8A4898', colorName: 'Monsoon Purple',
    peak: 'July (Jun–Sep)',
    windows: [W(d(6, 1), d(9, 15), d(7, 1), d(7, 31))] },
  { id: 'spa', code: 'SPA', common: 'Scarlet Bell Tree', botanical: 'Spathodea campanulata',
    origin: 'Uganda', color: '#C03818', colorName: 'Scarlet-Orange',
    peak: 'August–October',
    windows: [W(d(8, 1), d(10, 20), d(8, 15), d(10, 10))] },
  { id: 'pel', code: 'PEL', common: 'Copper Pod', botanical: 'Peltophorum pterocarpum',
    origin: 'South / SE Asia', color: '#C87820', colorName: 'Copper Gold',
    peak: 'October (Sep–Nov)',
    windows: [W(d(9, 15), d(11, 30), d(10, 1), d(10, 31))] },
];

export const ARCHITECTS = [
  { id: 'krumbiegel', name: 'Gustav Krumbiegel', era: 'Bangalore · 1908',
    theme: 'Civic Succession',
    logic: 'Designing at the scale of infrastructure — flowering trees as a public clock to ensure a city never loses its bloom across twelve months.' },
  { id: 'sackville-west', name: 'Vita Sackville-West', era: 'Sissinghurst · 1930s',
    theme: 'Chromatic Narrative',
    logic: 'Extreme restraint. A single hue forces the eye to notice texture, fragrance, and the subtle shift of light across the day.' },
  { id: 'oudolf', name: 'Piet Oudolf', era: 'High Line · 2000s',
    theme: 'Structural Lifecycle',
    logic: "The New Perennial movement — value the plant from seed to decay. It isn't just the flower, it's the skeleton in winter." },
  { id: 'chatto', name: 'Beth Chatto', era: 'Essex · 1960s',
    theme: 'Environmental Fitness',
    logic: 'Right Plant, Right Place. Soil and sun — not the human — have the final say.' },
  { id: 'corner', name: 'James Corner', era: 'Field Operations · 2000s',
    theme: 'Urban Metabolism',
    logic: 'Integrating nature into the machine of the city. Modularity, resilience, agri-tecture.' },
  { id: 'burle-marx', name: 'Roberto Burle Marx', era: 'Rio · 1940s–80s',
    theme: 'Tropical Modernism',
    logic: 'The garden as a 2D painting from a 3D perspective. Bold sweeping curves and massive leaf textures — a living canvas.' },
];

export const SEASONS = [
  { id: 'winter',  name: 'Winter',  startMonth: 11, endMonth: 1 },
  { id: 'spring',  name: 'Spring',  startMonth: 2,  endMonth: 3 },
  { id: 'summer',  name: 'Summer',  startMonth: 4,  endMonth: 5 },
  { id: 'monsoon', name: 'Monsoon', startMonth: 6,  endMonth: 8 },
  { id: 'autumn',  name: 'Autumn',  startMonth: 9,  endMonth: 10 },
];

export const COLOR_FAMILY = {
  'bombax-ceiba': 'red', 'delonix-regia': 'red', 'spathodea': 'red',
  'butea-monosperma': 'orange', 'colvillea': 'orange',
  'tabebuia-rosea': 'pink', 'cassia-javanica': 'pink', 'samanea-saman': 'pink',
  'jacaranda': 'purple',
  'tabebuia-aurea': 'yellow', 'peltophorum': 'yellow', 'cassia-fistula': 'yellow', 'cassia-multijuga': 'yellow',
  'millingtonia': 'white',
};

export const FAMILY_SWATCH = {
  all: '#100F0C',
  red: '#E63946',
  pink: '#E26A8F',
  purple: '#7C6FCB',
  yellow: '#F5C518',
  orange: '#F08A3A',
  white: '#FAFAF7',
};
